# Generated by Django 3.2 on 2022-02-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('SICK', 'sick leave'), ('NORMAL', 'normal leave')], default='NORMAL', max_length=10),
        ),
    ]
